version: '3.9'
services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB=medicalcenter
      - JWT_SECRET=${JWT_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - CORS_ORIGINS=http://localhost:5173
    depends_on:
      - mongo
    ports:
      - '3000:3000'
  web:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - VITE_API_URL=http://localhost:3000/api
      - VITE_DEFAULT_LANG=ar
    ports:
      - '5173:5173'
  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
