openapi: 3.0.0
info:
  title: MedicalCenter API
  version: 1.1.0

paths:
  /api/visitor/register:
    post:
      summary: Register visitor & assign clinic
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                identifier:
                  type: string
      responses:
        '200':
          description: assigned clinic & queue number

  /api/analytics/overview:
    get:
      summary: Analytics overview

  /api/auth/login:
    post:
      summary: Login for admin users

  /api/auth/users:
    get:
      summary: List users (ADMIN+)
    post:
      summary: Create user (SUPER_ADMIN)

  /api/exams/types:
    get:
      summary: List exam types
  /api/exams/set:
    post:
      summary: Set visitor exam type for today

  /api/admin/features:
    get:
      summary: List feature flags
    post:
      summary: Upsert feature flag
  /api/admin/notes:
    get:
      summary: List notes
    post:
      summary: Add note
  /api/admin/notifications:
    get:
      summary: List notifications
    post:
      summary: Upsert notification
  /api/admin/pins/today:
    get:
      summary: List today's two-digit PINs per clinic
  /api/admin/pins/regen:
    post:
      summary: Force regenerate today's two-digit PINs
  /api/admin/pins/verify:
    post:
      summary: Verify clinic PIN
  /api/admin/reports/csv:
    get:
      summary: Download CSV report
  /api/admin/reports/preview:
    get:
      summary: Preview report data (Visitors & Visits)
  /api/admin/stats/overview:
    get:
      summary: Stats overview for charts
